#!/bin/sh

set -e

MOCO_VERSION=$(cat VERSION | sed s/-[0-9]*$//)
VERSION=$(cat VERSION)
BUILD_DIR=build

rm -rf $BUILD_DIR/tmp $BUILD_DIR/package $BUILD_DIR/release
mkdir -p $BUILD_DIR/tmp $BUILD_DIR/package/opt/mocorunner $BUILD_DIR/release

echo "Building version $VERSION..."

cd $BUILD_DIR
[ -f moco-runner-$MOCO_VERSION-standalone.jar ] || wget https://repo1.maven.org/maven2/com/github/dreamhead/moco-runner/$MOCO_VERSION/moco-runner-$MOCO_VERSION-standalone.jar
cd ..

cp $BUILD_DIR/moco-runner-$MOCO_VERSION-standalone.jar $BUILD_DIR/package/opt/mocorunner
cp -R package/* $BUILD_DIR/package

size=$(du -csh $BUILD_DIR/package | sed '1!d' | grep -oe "^[0-9]*")
sed 's/{{version}}/'${VERSION}'/g;s/{{size}}/'${size}'/g' package/DEBIAN/control > $BUILD_DIR/package/DEBIAN/control
sed 's/{{moco_version}}/'${MOCO_VERSION}'/g' package/usr/bin/mocorunner > $BUILD_DIR/package/usr/bin/mocorunner

fakeroot dpkg-deb -b -z9 $BUILD_DIR/package $BUILD_DIR/release/mocorunner_${VERSION}_all.deb

echo done